<div class="block-header">
    <h2 class="breadcrumb">CHANGELOGS</h2>
</div>
     
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>v1.1.2 <small>2019-01-13</small></h2>
            </div>
            <div class="body">
                <ul>
                    <li>[Fixed] few important bugs.</li>
                    <li>[Added] New API for the new native app.</li>
                    <li>[Improved] speed.</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>v1.1.1 <small>2018-11-21</small></h2>
            </div>
            <div class="body">
                <ul>
                    <li>[Fixed] few important bugs.</li>
                    <li>[Improved] speed.</li>
                </ul>
            </div>
        </div>
    </div>
     <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>v1.1 <small>2018-10-29</small></h2>
            </div>
            <div class="body">
                <ul>
                    <li>[Added] face filters using webcam.</li>
                    <li>[Added] watermark system on images</li>
                    <li>[Added] support for mp4 links.</li>
                    <li>[Added] night mode</li>
                    <li>[Added] url fetcher, fetch images from urls.</li>
                    <li>[Added] blacklist system, for ip, username, emails.</li>
                    <li>[Added] lazyload for explore page (loads faster)</li>
                    <li>[Added] activities system (likes, comments, follow)</li>
                    <li>[Added] the abililty for the user to choose if their profile should be found/indexed.</li>
                    <li>[Added] ReCaptcha check to forgot password form</li>
                    <li>[Added] Session manager in settings page</li>
                    <li>[Added] Contact us page</li>
                    <li>[Added] emojis support for posts and comments.</li>
                    <li>[Added] Playtube support, you can import videos from a site that uses playtube script.</li>
                    <li>[Added] verification badge & system.</li>
                    <li>[Added] report filtration/warnings system.</li>
                    <li>[Added] startup page, upload avatar, fill info, follow.</li>
                    <li>[Added] emebd system, users can emebd posts from PixelPhoto using iframe.</li>
                    <li>[Added] video views system.</li>
                    <li>[Added] ajax load for pages (now pages load without refreshing).</li>
                    <li>[Added] full API system for the upcoming native app + docs.</li>
                    <li>[Fixed] few important bugs.</li>
                    <li>[Improved] speed.</li>
                </ul>
            </div>
        </div>
    </div>
     <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>v1.0.3 <small>2018-08-13</small></h2>
            </div>
            <div class="body">
                <ul>
                    <li>Fixed few important bugs.</li>
                </ul>
            </div>
        </div>
    </div>
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>v1.0.2 <small>2018-07-27</small></h2>
            </div>
            <div class="body">
                <ul>
                    <li>Fixed bugs in firefox and in video thumbnail.</li>
                </ul>
            </div>
        </div>
    </div>
     <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>v1.0.1 <small>2018-07-26</small></h2>
            </div>
            <div class="body">
                <ul>
                    <li>Fixed bugs.</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>v1.0 <small>2018-07-20</small></h2>
            </div>
            <div class="body">
                <ul>
                    <li>First release.</li>
                </ul>
            </div>
        </div>
    </div>
</div>